apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xjrt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-xjrt@sha256:5f3326bdfe9be1102503759c8fa1d563de0cccb94aa9c5031d2a9e7aaab5b675
        name: my-nodejs
        resources: {}
status: {}
